import type { Property } from "@/lib/types";

export const MOCK_LISTINGS: Property[] = [
  {
    id: "1",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    title: "Appartement moderne 3 pièces — Bonanjo",
    description: "Superbe appartement rénové avec vue sur le port. Cuisine équipée, parquet, gardiennage 24h/24.",
    listing_type: "rental",
    property_type: "apartment",
    price: 350000,
    price_per_sqm: 5833,
    currency: "XAF",
    negotiable: true,
    city: "douala",
    neighborhood_id: "1",
    neighborhood: { id: "1", name: "Bonanjo", city: "douala", slug: "bonanjo", lat: 4.0511, lng: 9.7085 },
    area_sqm: 60,
    bedrooms: 2,
    bathrooms: 1,
    floor: 3,
    total_floors: 6,
    parking: true,
    furnished: false,
    features: ["Gardiennage", "Eau courante", "Groupe électrogène"],
    photos: [{ id: "p1", property_id: "1", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800", storage_path: "", is_primary: true, is_live_capture: false, order_index: 0 }],
    primary_photo_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    source: "user",
    verification_status: "verified",
    view_count: 142,
    contact_count: 8,
  },
  {
    id: "2",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    title: "Villa 5 chambres avec piscine — Bastos",
    description: "Magnifique villa standing dans le quartier diplomatique. Piscine, jardin paysager, garage 3 voitures.",
    listing_type: "sale",
    property_type: "villa",
    price: 185000000,
    price_per_sqm: 925000,
    currency: "XAF",
    negotiable: false,
    city: "yaounde",
    neighborhood_id: "4",
    neighborhood: { id: "4", name: "Bastos", city: "yaounde", slug: "bastos", lat: 3.8869, lng: 11.5197 },
    area_sqm: 200,
    bedrooms: 5,
    bathrooms: 3,
    floor: 0,
    parking: true,
    furnished: true,
    features: ["Piscine", "Jardin", "Groupe électrogène", "Eau de forage", "Sécurité"],
    photos: [{ id: "p2", property_id: "2", url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800", storage_path: "", is_primary: true, is_live_capture: false, order_index: 0 }],
    primary_photo_url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
    source: "agency",
    verification_status: "verified",
    view_count: 387,
    contact_count: 22,
  },
  {
    id: "3",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    title: "Studio meublé — Makepe",
    description: "Studio fonctionnel et lumineux, idéal pour jeune professionnel. Tout équipé.",
    listing_type: "rental",
    property_type: "apartment",
    price: 120000,
    price_per_sqm: 4000,
    currency: "XAF",
    negotiable: true,
    city: "douala",
    neighborhood_id: "3",
    neighborhood: { id: "3", name: "Makepe", city: "douala", slug: "makepe", lat: 4.0697, lng: 9.7589 },
    area_sqm: 30,
    bedrooms: 1,
    bathrooms: 1,
    parking: false,
    furnished: true,
    features: ["WiFi inclus", "Eau courante", "Cuisine équipée"],
    photos: [{ id: "p3", property_id: "3", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800", storage_path: "", is_primary: true, is_live_capture: false, order_index: 0 }],
    primary_photo_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    source: "scraper",
    verification_status: "pending",
    view_count: 56,
    contact_count: 3,
  },
  {
    id: "4",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    title: "Appartement 4 pièces — Omnisport",
    description: "Bel appartement proche des commerces et transports. Résidence sécurisée.",
    listing_type: "sale",
    property_type: "apartment",
    price: 55000000,
    price_per_sqm: 687500,
    currency: "XAF",
    negotiable: true,
    city: "yaounde",
    neighborhood_id: "5",
    neighborhood: { id: "5", name: "Omnisport", city: "yaounde", slug: "omnisport", lat: 3.8480, lng: 11.5021 },
    area_sqm: 80,
    bedrooms: 3,
    bathrooms: 2,
    floor: 2,
    total_floors: 4,
    parking: true,
    furnished: false,
    features: ["Résidence gardée", "Groupe électrogène", "Eau courante"],
    photos: [{ id: "p4", property_id: "4", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800", storage_path: "", is_primary: true, is_live_capture: false, order_index: 0 }],
    primary_photo_url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
    source: "agency",
    verification_status: "verified",
    view_count: 211,
    contact_count: 14,
  },
  {
    id: "5",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    title: "Terrain 500m² viabilisé — Kribi",
    description: "Terrain à bâtir en zone résidentielle, proche plage. Titre foncier disponible.",
    listing_type: "sale",
    property_type: "land",
    price: 12000000,
    price_per_sqm: 24000,
    currency: "XAF",
    negotiable: false,
    city: "kribi",
    area_sqm: 500,
    parking: false,
    furnished: false,
    features: ["Titre foncier", "Eau", "Électricité", "Proche plage"],
    photos: [{ id: "p5", property_id: "5", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800", storage_path: "", is_primary: true, is_live_capture: false, order_index: 0 }],
    primary_photo_url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
    source: "user",
    verification_status: "verified",
    view_count: 93,
    contact_count: 7,
  },
  {
    id: "6",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    title: "Duplex standing — Akwa",
    description: "Duplex de prestige en plein coeur d'Akwa. Finitions haut de gamme, vue panoramique.",
    listing_type: "rental",
    property_type: "house",
    price: 750000,
    price_per_sqm: 6250,
    currency: "XAF",
    negotiable: false,
    city: "douala",
    neighborhood_id: "2",
    neighborhood: { id: "2", name: "Akwa", city: "douala", slug: "akwa", lat: 4.0522, lng: 9.7145 },
    area_sqm: 120,
    bedrooms: 4,
    bathrooms: 2,
    floor: 1,
    total_floors: 2,
    parking: true,
    furnished: true,
    features: ["Vue panoramique", "Terrasse", "Cuisine équipée", "Sécurité", "Groupe électrogène"],
    photos: [{ id: "p6", property_id: "6", url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800", storage_path: "", is_primary: true, is_live_capture: false, order_index: 0 }],
    primary_photo_url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    source: "agency",
    verification_status: "verified",
    view_count: 178,
    contact_count: 11,
  },
];
